policies:
- type: commit
  spec:
    headerLength: 89
    dco: true
    gpg: false
    imperative: true
    conventional:
      types:
      - chore
      - docs
      - perf
      - refactor
      - style
      - test
