kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

services:
  - name: docker
    image: docker:19.03.12-dind
    entrypoint:
      - dockerd
    command:
      - --dns=8.8.8.8
      - --dns=8.8.4.4
      - --mtu=1440
      - --log-level=error
    privileged: true
    volumes:
      - name: docker-socket
        path: /var/run

steps:
  - name: conform
    image: autonomy/conform:c539351

  - name: build-dry-run
    image: plugins/docker
    environment:
      PLUGIN_MTU: "1440"
    settings:
      repo: autonomy/build-container
      dry_run: true
    when:
      event:
        - pull_request

  - name: build-and-push
    image: plugins/docker
    environment:
      PLUGIN_MTU: "1440"
    settings:
      repo: autonomy/build-container
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        exclude:
          - pull_request

volumes:
  - name: docker-socket
    temp: {}
