kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
  - name: setup-ci
    image: autonomy/build-container:latest
    commands:
      - git fetch --tags
      - install-ci-key
      - setup-ci
    volumes:
      - name: outer-docker-socket
        path: /var/outer-run
      - name: docker-socket
        path: /var/run
      - name: ssh
        path: /root/.ssh
      - name: buildx
        path: /root/.docker/buildx

  - name: build-dry-run
    image: autonomy/build-container:latest
    pull: always
    volumes:
      - name: outer-docker-socket
        path: /var/outer-run
      - name: docker-socket
        path: /var/run
      - name: ssh
        path: /root/.ssh
      - name: buildx
        path: /root/.docker/buildx
    commands:
      - docker buildx build -f Dockerfile -t autonomy/build-container .
      - docker buildx build -f Dockerfile.actions-runner-ubuntu-22.04 -t autonomy/build-container:actions-runner-ubuntu-22.04 .
    when:
      event:
        - pull_request

  - name: build-and-push
    image: autonomy/build-container:latest
    pull: always
    volumes:
      - name: outer-docker-socket
        path: /var/outer-run
      - name: docker-socket
        path: /var/run
      - name: ssh
        path: /root/.ssh
      - name: buildx
        path: /root/.docker/buildx
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
      - docker login --username "$${DOCKER_USERNAME}" --password "$${DOCKER_PASSWORD}"
      - docker buildx build -f Dockerfile -t autonomy/build-container --push .
      - docker buildx build -f Dockerfile.actions-runner-ubuntu-22.04 -t autonomy/build-container:actions-runner-ubuntu-22.04 --push .
    when:
      event:
        exclude:
          - pull_request

trigger:
  branch:
    exclude:
      - renovate/*
      - dependabot/*

services:
- name: docker
  image: docker:27.0-dind
  entrypoint:
  - dockerd
  commands:
  - --dns=8.8.8.8
  - --dns=8.8.4.4
  - --mtu=1500
  - --log-level=error
  privileged: true
  volumes:
  - name: docker-socket
    path: /var/run
  - name: outer-docker-socket
    path: /var/outer-run
  - name: buildx
    path: /root/.docker/buildx
  - name: ssh
    path: /root/.ssh

volumes:
  - name: outer-docker-socket
    host:
      path: /var/ci-docker
  - name: docker-socket
    temp:
      medium: memory
  - name: buildx
    temp:
      medium: memory
  - name: ssh
    temp:
      medium: memory

---
kind: pipeline
name: notify
type: kubernetes

clone:
  disable: true

steps:
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: proj-talos-maintainers
    when:
      status:
        - success
        - failure

trigger:
  branch:
    exclude:
      - renovate/*
      - dependabot/*
  status:
  - success
  - failure

depends_on:
  - default
