kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

services:
  - name: docker
    image: docker:19.03.3-dind
    entrypoint:
      - dockerd
    command:
      - --dns=8.8.8.8
      - --dns=8.8.4.4
      - --mtu=1440
      - --log-level=error
    privileged: true
    volumes:
      - name: docker-socket
        path: /var/run

steps:
  - name: conform
    image: autonomy/conform:c539351

  # This step is temporary until a new version of buildx is released with
  # support for the Kubernetes driver.
  - name: buildx
    image: docker:19.03.3
    commands:
      - apk add bash git make
      - git clone https://github.com/docker/buildx.git
      - cd buildx
      - git checkout 709ef36b4f10a9389fd9a806657c48a969909d85
      - make binaries
    volumes:
      - name: docker-socket
        path: /var/run

  - name: build-dry-run
    image: plugins/docker
    environment:
      PLUGIN_MTU: "1440"
    settings:
      repo: autonomy/build-container
      dry_run: true
    when:
      event:
        - pull_request

  - name: build-and-push
    image: plugins/docker
    environment:
      PLUGIN_MTU: "1440"
    settings:
      repo: autonomy/build-container
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        exclude:
          - pull_request

volumes:
  - name: docker-socket
    temp: {}
