---
kind: auto.CI
spec:
  compileGHWorkflowsOnly: true
---
kind: common.GHWorkflow
spec:
  jobs:
    - name: default
      buildxOptions:
        enabled: true
      runners:
        - self-hosted
        - pkgs
      steps:
        - name: build
          nonMakeStep: true
          command: make
        - name: login-to-registry
          conditions:
            - except-pull-request
          registryLoginStep:
            registry: ghcr.io
        - name: push
          conditions:
            - except-pull-request
          nonMakeStep: true
          command: make
          environment:
            PUSH: true
---
kind: common.Renovate
spec:
  customManagers:
    - customType: regex
      fileMatch:
        - ^Dockerfile$
      matchStrings:
        - '#\s+renovate:\s+datasource=(?<datasource>.*?)\s+depName=(?<depName>.*?)(?:\s+versioning=(?<versioning>.*?))?(?:\s+extractVersion=(?<extractVersion>.*?))?\sARG\s+.*?_VERSION=(?<currentValue>.*)'
      versioningTemplate: "{{#if versioning}}{{versioning}}{{else}}semver{{/if}}"
    - customType: regex
      fileMatch:
        - ^hack/scripts/setup-
      matchStrings:
        - '#\s+renovate:\s+datasource=(?<datasource>.*?)\s+depName=(?<depName>.*?)(?:\s+versioning=(?<versioning>.*?))?(?:\s+extractVersion=(?<extractVersion>.*?))?\sBUILDKIT_IMAGE=\".+:(?<currentValue>.*)\"'
      versioningTemplate: "{{#if versioning}}{{versioning}}{{else}}semver{{/if}}"
