FROM summerwind/actions-runner-dind:ubuntu-22.04
# renovate: datasource=github-releases depName=google/go-containerregistry
ARG CRANE_VERSION=v0.19.1
# renovate: datasource=github-releases depName=mikefarah/yq
ARG YQ_VERSION=v4.43.1
# renovate: datasource=github-releases depName=getsops/sops
ARG SOPS_VERSION=v3.8.1
USER root
RUN apt update && \
	apt upgrade -y && \
	apt install -y \
	--no-install-recommends \
	make \
	tmux \
	qemu-system \
	qemu-utils \
	socat \
	ovmf \
	swtpm \
	iptables \
	iproute2 \
	openssh-client \
	docker.io \
	diffoscope \
	gh

RUN curl -fSL https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64 -o /usr/bin/yq && chmod +x /usr/bin/yq
RUN curl -fSL https://github.com/google/go-containerregistry/releases/download/${CRANE_VERSION}/go-containerregistry_Linux_x86_64.tar.gz | tar xzf - -C /usr/local/bin/ crane
RUN curl -fSL https://github.com/getsops/sops/releases/download/${SOPS_VERSION}/sops-${SOPS_VERSION}.linux.amd64 -o /usr/bin/sops && chmod +x /usr/bin/sops
USER runner
