#!/bin/sh

set -eou pipefail

if [ -z "${SSH_KEY+x}" ]; then
    exit 0
fi

mkdir -p ~/.ssh
echo "${SSH_KEY}" | base64 -d > ~/.ssh/id_ed25519
chmod 400 ~/.ssh/id_ed25519

echo "Host 139.178.90.2" >> ~/.ssh/config
echo "  User root" >> ~/.ssh/config
echo "  StrictHostKeyChecking no" >> ~/.ssh/config
