#!/bin/sh

set -ex

export TAG=$(git log --oneline --format=%B -n 1 HEAD | head -n 1 | sed -r "s/^release\((.*)\):.*$/\\1/")

function setup_buildkit() {
  docker buildx create \
    --name ci --buildkitd-flags "--allow-insecure-entitlement security.insecure" --driver-opt image=moby/buildkit:master \
    --platform linux/amd64 \
    --driver docker-container  \
    --use unix:///var/outer-run/docker.sock

  docker buildx create \
    --name ci --buildkitd-flags "--allow-insecure-entitlement security.insecure" --driver-opt image=moby/buildkit:master \
    --platform linux/arm64 \
    --append \
    tcp://docker-arm64.ci.svc:2376

  docker buildx inspect --bootstrap
}


function setup_tags() {
  git fetch --tags

  if [ $(git tag -l "$TAG") ]; then
    echo "Tag exists: $TAG"
    return
  fi

  if [ -n $TAG ]; then
    echo "Creating temporary tag: $TAG"
    git tag -a $TAG -m "$TAG"
  fi
}

sleep 5
setup_buildkit
setup_tags
