#!/bin/sh

set -eou pipefail

# renovate: datasource=github-releases depName=moby/buildkit
BUILDKIT_IMAGE="docker.io/moby/buildkit:v0.12.2"

docker buildx create --driver docker-container --platform linux/amd64 --name xbuild --use --driver-opt image=${BUILDKIT_IMAGE} --config /usr/local/bin/buildkit.toml
docker buildx create --append --name xbuild --platform linux/arm64 tcp://docker-arm64.ci.svc:2376 --driver-opt image=${BUILDKIT_IMAGE} --config /usr/local/bin/buildkit.toml
